datasource.url=jdbc:mysql://127.0.0.1:3306/hong?&serverTimezone=Asia/Shanghai
datasource.username=root
datasource.password=123456
datasource.driver-class-name=com.mysql.jdbc.Driver
datasource.hikari.connection-timeout=30000
datasource.hikari.idle-timeout=60000
datasource.hikari.maximum-pool-size=5
datasource.hikari.minimum-idle=1